server:
  port: 8082
  servlet:
     context-path: /v1.0/
spring:
  application:
    name: api-mobile-marvel
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=master
    username: sa
    password: 123456789!aA
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:  
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate: 
        default_schema: dbo    

marvel: 
  url: http://localhost:8081
  method:
    get-character: /v1.0/characters
    get-comic-by-name: /v1.0/comics
    get-characters-by-comic: /v1.0/comics/{comicId}/characters
    get-characters-by-serie: /v1.0/series/{seriesId}/characters
    get-comics-by-character: /v1.0/characters/{characterId}/comics
    get-image-and-desc-by-character: /v1.0/characters
    get-list-by-comic: /v1.0/comics
    get-comic-by-id: /v1.0/comics/{comicId}
    get-comic-by-creator: /v1.0/creators
    get-images-all-characters: /v1.0/characters
    post-log: /v1.0/log


authorization: 
  jwt:
    application: api-mobile-marvel
    secret: m4rv3l
    header: Authorization
    expiration: 3600000
    route:
      authentication:
        path: /auth
  
