FROM openjdk:14-jdk-alpine

RUN apk add --no-cache tzdata
ENV TZ CST
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /api-mobile-marvel

COPY target/api-mobile-marvel.jar ./

EXPOSE 8082

